### ISSUE TITLE
Submodule tracks commit instead of branch

### ISSUE THREAD

**Issue by haslinger** [c3wien/c3w.at#1]
is it on purpose, that the pages submodule tracks a commit instead of following the master branch?

**Comment by oe1rfc** [comment]
nope, forgot -b when adding the repos, should be fixed in 6d4492f93d31e081f77b8b6302fbe398e845d310
Basic idea is having a master (staging) and stable repo, going to https://toaster.c3w.at and https://c3w.at respectively.
